//! Build script for generating constants from `shared/constants.json`
//!
//! Reads the shared JSON constants file, generates Rust enum types with
//! `as_str`, `parse`, and `Display` implementations, and writes the output
//! into `src/generated/`. Also produces `src/generated/mod.rs` with the
//! correct `include_str!` path for the shared README
//!
//! Author: aav
#![allow(
    clippy::panic,
    clippy::expect_used,
    clippy::unwrap_used,
    reason = "if filenames malformed, contents malformed, dirs not made, then build should always fail/panic"
)]
// --------------------------------------------------
// external
// --------------------------------------------------
use convert_case::{Case, Casing};
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};
use serde_json::Value;
use std::{fs, path::Path};

// --------------------------------------------------
// constants - generated (this is sink)
// --------------------------------------------------
const GENERATED_DIR: &str = "src/generated";
const GENERATED_MOD: &str = const_str::concat!(GENERATED_DIR, "/mod.rs");

// --------------------------------------------------
// constants - shared (this is ONE source)
// --------------------------------------------------
const SHARED_DIR: &str = "shared";
const SHARED_README: &str = const_str::concat!(SHARED_DIR, "/README.md");
const SHARED_CONSTANTS_SRC: &str = const_str::concat!(SHARED_DIR, "/constants.json");
const SHARED_CONSTANTS_DEST: &str = const_str::concat!(GENERATED_DIR, "/shared_constants.rs");

// --------------------------------------------------
// build
// --------------------------------------------------
fn main() {
    // --------------------------------------------------
    // tell cargo to rerun this script when shared/ changes
    // --------------------------------------------------
    println!("cargo:rerun-if-changed=shared/*");
    // --------------------------------------------------
    // read and parse the shared constants JSON file
    // --------------------------------------------------
    let json_str = fs::read_to_string(SHARED_CONSTANTS_SRC)
        .unwrap_or_else(|e| panic!("failed to read {SHARED_CONSTANTS_SRC}: {e}"));
    let json: serde_json::Value = serde_json::from_str(&json_str)
        .unwrap_or_else(|e| panic!("failed to parse {SHARED_CONSTANTS_SRC} as JSON: {e}"));
    // --------------------------------------------------
    // resolve the destination file path and derive the
    // snake_case module name from the filename
    // --------------------------------------------------
    let dest_path = Path::new(SHARED_CONSTANTS_DEST);
    let dest_fname = dest_path
        .file_name()
        .and_then(|n| n.to_str())
        .expect("filename malformed inside of {SHARED_CONSTANTS_DEST}")
        .strip_suffix(".rs")
        .expect("filename inside of {SHARED_CONSTANTS_DEST} does not end with .rs")
        .to_case(Case::Snake);
    // --------------------------------------------------
    // ensure the generated directory exists
    // --------------------------------------------------
    dest_path.parent().map(fs::create_dir_all);
    // --------------------------------------------------
    // compute the include_str! path from the generated
    // directory to the shared README
    // --------------------------------------------------
    let readme_relative_path = get_relative_dir_for_include_str(
        Path::new(SHARED_README).canonicalize().unwrap(),
        Path::new(GENERATED_DIR).canonicalize().unwrap(),
    );
    // --------------------------------------------------
    // write the generated mod.rs with the correct
    // include_str! path embedded
    // --------------------------------------------------
    let mod_rs_content = format!(
        r#"//! Generated constants and shared type definitions
//!
//! This module is produced by `build.rs` at compile time from
//! `shared/constants.json`. Do not edit this file or its submodules by hand -
//! changes will be overwritten on the next build
//!
//! Author: aav

mod {dest_fname};
#[doc = include_str!("{readme_relative_path}")]
pub mod shared {{
    pub use super::{dest_fname}::*;
}}"#
    );
    fs::write(GENERATED_MOD, mod_rs_content).expect("failed to write mod.rs - try rebuild?");
    // --------------------------------------------------
    // walk the JSON and accumulate generated enum tokens
    // --------------------------------------------------
    let mut tokens = TokenStream::new();
    make_enums_from_json("", &json, &mut tokens);
    // --------------------------------------------------
    // write the generated token stream to the destination
    // --------------------------------------------------
    fs::write(dest_path, tokens.to_string())
        .expect("failed to write tokens to file - try rebuild?");
}

/// Computes the relative path from `dir` to `path_for_include_str` for use in `include_str!`
///
/// Strips the `dir` prefix from `path_for_include_str` to produce a relative
/// path. If `path_for_include_str` is not inside `dir`, the absolute path is
/// returned unchanged. Backslashes are normalized to forward slashes for
/// cross-platform compatibility
///
/// # Arguments
///
/// * `path_for_include_str` - The canonicalized path to the file being included
/// * `dir` - The canonicalized directory the generated file lives in
///
/// # Example
///
/// ```rust,ignore
/// use std::path::PathBuf;
///
/// let path = PathBuf::from("/abs/path/to/file.txt");
/// let dir = PathBuf::from("/abs/path/to");
/// let result = get_relative_dir_for_include_str(path, dir);
/// assert_eq!(result, "file.txt");
/// ```
fn get_relative_dir_for_include_str(
    path_for_include_str: std::path::PathBuf,
    dir: std::path::PathBuf,
) -> String {
    let relative_path = path_for_include_str
        .strip_prefix(&dir)
        .unwrap_or(&path_for_include_str);
    relative_path.to_string_lossy().replace("\\", "/")
}

/// Recursively walks a JSON value and appends generated enum tokens to the stream
///
/// JSON arrays produce a single enum whose name is derived from the `path`
/// argument converted to `PascalCase`. JSON objects cause recursive descent,
/// with each key appended to `path` (separated by `_`). All other JSON value
/// types are ignored. See [`impl_enum`] for the token shape produced per enum
///
/// # Arguments
///
/// * `path` - Accumulated key path used to derive the enum name (empty at root)
/// * `value` - The current JSON value being processed
/// * `tokens` - The token stream to append generated code to
fn make_enums_from_json(path: &str, value: &Value, tokens: &mut TokenStream) {
    match value {
        Value::Array(arr) => {
            let enum_ident = format_ident!("{}", path.to_case(Case::Pascal));
            let variants: Vec<_> = arr
                .iter()
                .filter_map(|v| v.as_str())
                .map(|v| format_ident!("{}", v.to_case(Case::Pascal)))
                .collect();
            let variant_strings: Vec<_> = arr.iter().filter_map(|v| v.as_str()).collect();
            tokens.extend(impl_enum(
                &enum_ident,
                variants.as_slice(),
                variant_strings.as_slice(),
            ));
        }
        Value::Object(map) => {
            for (k, v) in map {
                let new_path = if path.is_empty() {
                    k.clone()
                } else {
                    format!("{}_{}", path, k)
                };
                make_enums_from_json(&new_path, v, tokens);
            }
        }
        _ => {}
    }
}

#[inline]
/// Generates the full token stream for a single enum from its variants
///
/// Produces a `#[derive(...)]` enum, an `impl` block with `ALL`, `STRS`,
/// `as_str`, and `parse`, and a `Display` impl that delegates to `as_str`
/// Input idents must already be in `PascalCase`; variant strings are the
/// canonical `snake_case` representations used for serialization and parsing
///
/// # Arguments
///
/// * `enum_ident` - The `PascalCase` identifier for the generated enum
/// * `variants` - Slice of `PascalCase` variant identifiers
/// * `variant_strings` - Slice of canonical `snake_case` strings, one per variant
///
/// # Example
///
/// ```rust,ignore
/// // enum_ident = ThemeName
/// // variants   = [Forest, Clay, ...]
/// // variant_strings = ["forest", "clay", ...]
/// //
/// // generates:
/// // pub enum ThemeName { Forest, Clay, ... }
/// // impl ThemeName { pub const fn as_str(...) ... }
/// // impl Display for ThemeName { ... }
/// ```
fn impl_enum(enum_ident: &Ident, variants: &[Ident], variant_strings: &[&str]) -> TokenStream {
    quote! {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[allow(dead_code)]
        #[doc = concat!(" [`", stringify!(#enum_ident), "`] is an enum loaded from `shared/constants.json`")]
        #[doc = " during compile-time"]
        pub enum #enum_ident {
            #( #variants, )*
        }

        #[allow(dead_code)]
        #[doc = concat!(" [`", stringify!(#enum_ident), "`] implementation")]
        impl #enum_ident {
            /// All variants in declaration order
            pub const ALL: &[Self] = &[ #( Self::#variants, )* ];

            /// All variant strings in declaration order
            pub const STRS: &[&str] = &[ #( #variant_strings, )* ];

            /// Returns the canonical `&'static str` representation
            pub const fn as_str(&self) -> &'static str {
                match self {
                    #( Self::#variants => #variant_strings, )*
                }
            }

            /// Parses from the canonical string, or `None` if unrecognized
            pub fn parse(s: &str) -> Option<Self> {
                match s {
                    #( #variant_strings => Some(Self::#variants), )*
                    _ => None,
                }
            }
        }

        #[doc = concat!(" [`", stringify!(#enum_ident), "`] implemtation of [`std::fmt::Display`]")]
        impl ::std::fmt::Display for #enum_ident {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
    }
}
