admin_port = 15204
download_port = 15205
admin_host = "0.0.0.0"
# admin_token = "1234"
admin_password = "admin"
download_host = "192.168.1.75"
base_path = "/mnt/arpadnas/vault"
buffer_size = 8192
max_request_size = 10485760
enable_https = false
